import { Montserrat } from "next/font/google";

import "./globals.css";

import Header from "@/components/Header";
import Providers from "@/apollo/provider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "CMS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
