import { Montserrat } from "next/font/google";
import { ApolloProvider } from "@apollo/client";

import useApollo from "@/hooks/useApollo";

import "./globals.css";

import Header from "@/components/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "CMS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const client = useApollo(children);

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ApolloProvider client={client}>
          <Header />
          {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
